server:
  port: 8767

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: service-gateway
  profiles:
    active: query_route

#After Route Predicate Factory
---
spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          #uri: http://httpbin.org:80/get
          uri: http://localhost:8765
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
  profiles: after_route

#Header Route Predicate Factory
---
spring:
  cloud:
    gateway:
      routes:
        - id: header_route
          uri: http://httpbin.org:80
          #uri: http://localhost:8765
          predicates:
            - Header=X-Request-Id, \d+
  profiles: header_route

#Cookie Route Predicate Factory
---
spring:
  cloud:
    gateway:
      routes:
        - id: cookie_route
          uri: http://httpbin.org:80/get
          predicates:
            - Cookie=name, panyang
  profiles: cookie_route

#Host Route Predicate Factory
---
spring:
  cloud:
    gateway:
      routes:
        - id: host_route
          uri: http://httpbin.org:80
          predicates:
            - Host=**.hystrix.com
  profiles: host_route

#Method Route Predicate Factory
---
spring:
  cloud:
    gateway:
      routes:
        - id: method_route
          uri: http://httpbin.org:80/get
          predicates:
            - Method=GET
  profiles: method_route

#Path Route Predicate Factory
---
spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://httpbin.org:80
          predicates:
            - Path=/get/{segment}
  profiles: path_route

#Query Route Predicate Factory
---
spring:
  cloud:
    gateway:
      routes:
        - id: query_route
          uri: http://localhost:8765
          predicates:
            #参数名和值都匹配才转发
            - Query=name, panyang
            #参数名匹配就可以转发
            #- Query=name
  profiles: query_route
